### ISSUE TITLE
Typo in Exp / Log maps in Appendix D

### ISSUE THREAD

**Issue by ferreram** [artivis/manif#113]
Hi guys,
Thanks for sharing this work!

I just wanted to let you know that there is a typo about V(&theta;) in Appendix D.  The V(&theta;) (Eq.174) does not match the left Jacobian of SO(3) (Eq. 145), it misses the powers' values on the denominators.

Cheers,
Maxime

**Comment by joansola** [comment]
Hi Maxime,

Thanks for reaching out!

I think however that we have it right. Just notice that (145) uses [\bf\theta]_x, whereas (174) uses [\bf u]_x. Since {\bf \theta} = {\bf u} * \theta, the two equations match. Maybe we could re-write one of them to avoid this confusion!

If this is not the case in your copy, please let us know. We have had some other typos in the past and this could be one of them. Please use V5 of the paper in Arxiv for piece of mind.

Joan

**Comment by ferreram** [comment]
Hi Joan,

Oh yes, you are right.  Thanks for the clarification!  

Maybe just adding a note on the fact that V(&theta;) is equivalent to (145) in this case could be nice?

Thanks again,
Maxime

**Comment by joansola** [comment]
Yes I think I'll add some note for this, thanks!
