### ISSUE TITLE
make core types nothrow move constructible

### ISSUE THREAD

**Issue by mindbeast** [artivis/manif#172]
Most of the core types make a user-defined destructor, turning off automatic generation of a no-throw move constructor. This can be easily tested with a compile time assertion: 

static_assert(std::is_nothrow_move_constructible<SE3d>::value, "should be nothrow move constructible");

Following the "rule of zero" across the library will make the types nothrow move constructible, and thus faster to place in standard containers.

**Comment by mindbeast** [comment]
#173

**Comment by artivis** [comment]
Hi, thanks for reporting this.
I have actually been paying a closer look to what's automatically generated and what's not, especially to comply with g++8/9 in #147. And while doing so I noticed that Eigen move semantic was broken for fixe-size vectors and was fix only recently (see [here](https://gitlab.com/libeigen/eigen/-/merge_requests/138)). With this in mind I left the move semantic aside in `manif` altogether for future development.
Have you quantified in any ways the benefit of your fix in #173? I'd expect it to be negligible given that Eigen bug.

**Comment by mindbeast** [comment]
It's can be non-negligible. Any other types that contain these types and follow rule of zero will lose their move-noexcept-ness.

E.g. https://godbolt.org/z/scr6x6

std::vector will no longer be able to use move when doing a vector resize with any of those types. So it can be non-trivial. I don't have a benchmark though, if that's what your asking. I added a pull request https://github.com/artivis/manif/pull/173, not sure if you saw it. It's a fairly simple fix.

**Comment by artivis** [comment]
I understand your concern for classes that contains a `manif` type and I agree that this issue should be addressed.
I have seen your PR #173 and indeed the fix is simple, but so is declaring a default move constructor, e.g. https://godbolt.org/z/3zaaYr.

The implications of either solution have to be investigated but as of now I would lean toward declaring a default move constructor since I have to explicitly define some of the default operations (see #147).
