### ISSUE TITLE
`CeresObjectiveFunction` residual should be of dimension 6

### ISSUE THREAD

**Issue by ojura** [artivis/manif#221]
Why do we take the norm of the residual from the target group element in `CeresObjectiveFunction`? This makes the residual a scalar, effectively limiting the solver's steps to a gradient descent.

I see there are some TODOs in there for implementing custom Jacobians, which is nice :)

But just returning the residual as the result of a left/right minus (maybe the average of the two?) of dimension 6 would be an improvement, wouldn't it? And since the result of the minus operator is a vector in the tangent space, it can also be scaled with the weight.

I don't see the benefits of taking the norm there, AFAIK it's a common mistake to do that when writing Ceres cost funtions since it conceals the structure of the optimization problem from the solver.

**Comment by artivis** [comment]
Hi,

First of all, note that those Ceres helpers are meant to be some reference implementations for generic (template) wrappers more than plug-n-play prod-ready bits. They exists only to showcase how one can design such generic wrapper for one's own application. As such `CeresObjectiveFunction`'s cost is a scalar while `CeresConstraintFunctor`'s cost is a vector. From there you should implement your own cost function.

Concerning the TODOs you mentioned, they will most likely never happen. As mentioned in [the doc related to Ceres](https://artivis.github.io/manif/cpp/md_pages_cpp__on_the_use_with__ceres.html), the Jacobians provided by `manif` can not plugged directly in Ceres. That's a known Ceres feature/limitation (see e.g. discussions https://github.com/ceres-solver/ceres-solver/issues/387 and https://github.com/ceres-solver/ceres-solver/issues/615). That's why the documentation mention that `manif` is `Ceres::Jet` compliant. If you absolutely need the analytic Jacs, you should have a look at [Sophus](https://github.com/strasdat/Sophus).

> the result of a left/right minus (maybe the average of the two?)

Mind that the left minus results in a vector in the *global frame* while the right minus results in a vector in the *local frame*. An average wouldn't make sense.

For sure taking the norm isn't always a benefit (of course) but I wouldn't call it mistake either, it depends on your problem/application. Concealing part of your problem can prove beneficial in practice (e.g. the tip goal in a receding horizon planner).

**Comment by ojura** [comment]
Hi, thanks on a quick response and for clarifying the readiness level! Being Jet/autodiff compliant is a huge benefit in terms of code clarity and simplicity, and in being able to rapidly prototype different cost functions. I haven’t yet encountered a scenario where I would have to write custom analitical Jacobians because of performance, and I hope I won’t :)

That being said, I wanted to ask one more thing. I’m aware of the difference between expressing the difference in global and local frames. Let’s say that I have a drifty trajectory which contains a loop that I want to close by smoothing the trajectory. Let’s say that the beginning of the loop is pose A, ending is pose B, and the desired relative pose between the two is exactly identity (could be something small, but let’s stick with identity for simplicity’s sake). In this case, I can use either A (-) B or B (-) A as a residual, since it will be a zero vector when they are identical. I have to pick one of these, but introducing some kind of asymmetry here seems wrong. That’s why I thought it might be a good idea to average them out, but maybe I’m overthinking it.

It makes sense to use Pose_k (-) Pose_k-1 as the residual for odometry contraints between adjacent sequential poses (as you implemented in `CeresConstraintFunctor`), but it feels wrong to do that when constraining distant poses which have no meaningful ordering.

I still have to brush up on my theoretical knowledge here, this seems related to the Lienbracket commutator, but the Lie group theory is a deep rabbit hole :)
