### ISSUE TITLE
Typo in Table 1 of the paper

### ISSUE THREAD

**Issue by ferreram** [artivis/manif#89]
Hi guys,
Just to let you know, I think there is a typo in Table 1 in the paper.  In the _Exp(T)_ matrix of SE(3), there should be a 1 instead of a 0 in the bottom right side.
Anyway, thanks for this great work!
Cheers

**Comment by joansola** [comment]
Hi ferreram, thanks for writing!

Which version of the paper are you referring to? 

There is indeed a typo, but in SE2, and the 1 at the bottom right must change to 0, that is:

`M = exp( [theta_x , p ; 0 , 0] ) = [ R , p ; 0 , 1 ]`

This is fixed in my current latex version but I have to upload it to Arxiv -- that would be v6 of the paper.

Anyway thanks a lot!!

**Comment by ferreram** [comment]
I was referring to the last version of the paper on arxiv (v5 I think).
Yes you're right it is on SE(2), I got confused with SE(3). 
Thanks again for your work!

**Comment by joansola** [comment]
Version V6 is now available on Arxiv. I recommend you switch to it for improved explanations and typo fixes.
