### ISSUE TITLE
Normalization issue for SO3 with multiple rplus operations

### ISSUE THREAD

**Issue by MichalNowicki** [artivis/manif#94]
Thanks for this work.

We are considering using _manif_ in our EKF implementation that constantly updates the rotation estimate (SO3) with angular velocity updates stored in Lie algebra. It is working on our own simple LieAlgebra library but it crashes after several iterations when using _manif_. Minimal code that reproduces the error:
```
 // Identity
manif::SO3d R = manif::SO3d(0, 0, 0, 1.0);

// Some angular velocity
manif::SO3Tangentd Om = Eigen::Vector3d(0.001, 0.0, 0.0);

// New orientation
for (int i = 0 ; i < 1000; i++) {
   std::cout << i << std::endl;
   R = R.plus(Om);
}
```
I guess it is related to pull request https://github.com/artivis/manif/pull/72 and I understand your arguments but as for now I think it is necessary to perform R.normalize() after every change to make sure it is still a proper quaternion. Maybe it should be added to the examples concerning EKF/optimization?

**Comment by MichalNowicki** [comment]
Corrected code if someone encounters the same issue:
```
for (int i = 0 ; i < 1000; i++) {
   R = R.plus(Om);
   R.normalize();
}
```

**Comment by joansola** [comment]
Hi Michal, thanks for pointing this out.

It is strange. Some time ago, I was trying in Eigen to produce the same error. I did one million iterations of quaternion composition and regarded the norm of the result at the end. It was 1.000000 and a lot of zeros.

Your experience with much fewer iterations makes me re-consider what I did. I will come later with more comments. Since we re-use quite a lot of Eigen algebra inside manif, the following comes to mind:

  - maybe our exp() function is wrong;
  - maybe the small-angle approximations are too severs -- though you use 0.001 which is not that small.
  - maybe my experiment and yours are not equivalent in some sense.

**Comment by MichalNowicki** [comment]
For now, from my mobile - it was constructor message about norm not being 1.0. From my debugging, it is almost 1.0 but check is very strict with eps 1e-15. I can post exact message later

**Comment by joansola** [comment]
The code:
```c++
    // Identity
   manif::SO3d R = manif::SO3d(0, 0, 0, 1.0);

   // Some angular velocity
   manif::SO3Tangentd Om = Eigen::Vector3d(0.001, 0.0, 0.0);

   // New orientation
   for (int i = 0 ; i < 1000; i++) {
      R = R.plus(Om);
      std::cout << "iteration " << i << ": deviation from unit squaredNorm: " << R.coeffs().squaredNorm() - 1.0 << std::endl;
   }
```
produces:
```bash
[ RUN      ] TEST_SO3.TEST_SO3_NORM_STABILITY
iteration 0: deviation from unit squaredNorm: 2.22045e-16
iteration 1: deviation from unit squaredNorm: 2.22045e-16
iteration 2: deviation from unit squaredNorm: 4.44089e-16
iteration 3: deviation from unit squaredNorm: 6.66134e-16
iteration 4: deviation from unit squaredNorm: 6.66134e-16
iteration 5: deviation from unit squaredNorm: 6.66134e-16
iteration 6: deviation from unit squaredNorm: 8.88178e-16
iteration 7: deviation from unit squaredNorm: 8.88178e-16
iteration 8: deviation from unit squaredNorm: 8.88178e-16
iteration 9: deviation from unit squaredNorm: 1.11022e-15
iteration 10: deviation from unit squaredNorm: 1.11022e-15
iteration 11: deviation from unit squaredNorm: 1.11022e-15
iteration 12: deviation from unit squaredNorm: 1.11022e-15
iteration 13: deviation from unit squaredNorm: 1.33227e-15
iteration 14: deviation from unit squaredNorm: 1.33227e-15
iteration 15: deviation from unit squaredNorm: 1.55431e-15
iteration 16: deviation from unit squaredNorm: 1.77636e-15
iteration 17: deviation from unit squaredNorm: 1.77636e-15
unknown file: Failure
C++ exception with description "SO3 constructor argument not normalized !" thrown in the test body.
[  FAILED  ] TEST_SO3.TEST_SO3_NORM_STABILITY (0 ms)
```
so it seems really that our test is very strict. We will address this shortly. In the meantime, maybe you want to change the `eps_s=1e-15` into `eps=1e-10` and see how it goes for your projects.

thanks again for the feedback.

**Comment by MichalNowicki** [comment]
Thanks! I will check it and close if it is working fine

**Comment by artivis** [comment]
@MichalNowicki Thanks for reporting this issue. I was expecting it after merging #93, but not so 'quickly' - in the sense of so few iterations.  
We will have to clearly identify which operations lead to the most drift and simply re-normalize after a small check. However we'll have to think carefully about it in order to minimize the performance penalty.
In the meantime you can either, as @joansola suggested, increase `eps_s` value if that works for you, or checkout the library before #93 as follows,
```terminal
$ cd manif
$ git checkout 8b3c004ca635182183bc2ee0db9f155ca7d407ec
```

**Comment by MichalNowicki** [comment]
I just tested PR https://github.com/artivis/manif/pull/97 and it works fine for me. Thanks for really fast help!
